spring:
  jpa:
    open-in-view: false

---

spring:
  config:
    activate:
      on-profile:
        - local
        - default
  #  flyway:
  #    enabled: true
  #    baseline-on-migrate: true
  #    baseline-version: 1
  #  jpa:
  #    hibernate:
  #      ddl-auto: validate
  #    properties:
  #      hibernate:
  #        show_sql: true
  #        format_sql: true
  #  datasource:
  #    driver-class-name: com.mysql.cj.jdbc.Driver
  #    url: jdbc:mysql://localhost:3307/wypl
  #    username: root
  #    password: 1234
  flyway:
    enabled: false
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:db
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2

---

spring:
  config:
    activate:
      on-profile: dev
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 1
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://43.203.229.26:8301/wypl
    username: root
    password: wyplA602!@

---

spring:
  config:
    activate:
      on-profile:
        - blue
        - green
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 1
  jpa:
    hibernate:
      ddl-auto: validate
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://43.203.229.26:18301/wypl
    username: root
    password: wyplA602!@