spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 885938171761-afchfc79qg320oua3llroitjbe01m8hq.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile

---

spring:
  config:
    activate:
      on-profile:
        - local
        - default
  security:
    oauth2:
      client:
        registration:
          google:
            redirect-uri: http://localhost:5173/login/oauth2/code/google

---

spring:
  config:
    activate:
      on-profile: dev
  security:
    oauth2:
      client:
        registration:
          google:
            redirect-uri: https://dev.wypl.site/login/oauth2/code/google

---

spring:
  config:
    activate:
      on-profile:
        - blue
        - green
  security:
    oauth2:
      client:
        registration:
          google:
            redirect-uri: https://wypl.site/login/oauth2/code/google