spring:
  config:
    activate:
      on-profile:
        - local
        - default
  data:
    redis:
      port: 6379
      host: 127.0.0.1

---

spring:
  config:
    activate:
      on-profile: dev
  data:
    redis:
      url: jdbc:redis://43.203.229.26:8302/
      password: wyplA602!@
      host: 43.203.229.26
      port: 8302

---

spring:
  config:
    activate:
      on-profile:
        - blue
        - green
  data:
    redis:
      url: jdbc:redis://43.203.229.26:18302/
      password: wyplA602!@
      host: 43.203.229.26
      port: 18302
