spring:
  config:
    activate:
      on-profile:
        - local
        - default

de:
  flapdoodle:
    mongodb:
      embedded:
        version: 4.0.2

---

spring:
  config:
    activate:
      on-profile: dev
  data:
    mongodb:
      host: 43.203.229.26
      port: 8303
      database: wypl
      username: wypl
      password: wyplA602!@
      authentication-database: admin

---

spring:
  config:
    activate:
      on-profile:
        - blue
        - green
  data:
    mongodb:
      host: 43.203.229.26
      port: 18303
      database: wypl
      username: wypl
      password: wyplA602!@
      authentication-database: admin