version: "3"

services:

  # CI-CD
  jenkins_container:
    image: jenkins/jenkins:lts
    ports:
      - "${JENKINS_UI_PORT}:8080"
      - "${JENKINS_AGENT_PORT}:50000"
    volumes:
      - ./data/jenkins/data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

