spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 885938171761-afchfc79qg320oua3llroitjbe01m8hq.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: http://127.0.0.1:8080/login/oauth2/code/google
            scope:
              - email
              - profile