# Use root/example as user/password credentials
version: "3"

services:
  # Redis
  redis_container_test:
    container_name: redis_container_test
    image: redis
    ports:
      - 8888:6379
    volumes:
      - ./data/redis/data:/data
      - ./data/redis/config/redis.conf:/usr/local/etc/redis/redis.conf
    restart: on-failure
    command: ["redis-server", "/usr.local/etc/redis/redis.conf"]

